{{- if .Values.elasticsearch.enabled }}
{{- if .Values.elasticsearch.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nomad-oasis.fullname" . }}-elastic
  labels:
    {{- include "nomad-oasis.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.elasticsearch.persistence.storageClass }}
  storageClassName: {{ .Values.elasticsearch.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.elasticsearch.persistence.size }}
{{- end }}
{{- end }}
