{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nomad-oasis.fullname" . }}-mongo
  labels:
    {{- include "nomad-oasis.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  clusterIP: None  # Headless service
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    {{- include "nomad-oasis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}
