{{- if .Values.temporal.enabled }}
{{- if .Values.temporal.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nomad-oasis.fullname" . }}-postgresql
  labels:
    {{- include "nomad-oasis.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    {{- include "nomad-oasis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
{{- end }}
