{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nomad-oasis.fullname" . }}-rabbitmq
  labels:
    {{- include "nomad-oasis.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  serviceName: {{ include "nomad-oasis.fullname" . }}-rabbitmq
  replicas: 1
  selector:
    matchLabels:
      {{- include "nomad-oasis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq
  template:
    metadata:
      labels:
        {{- include "nomad-oasis.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.11.5-alpine
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              value: {{ .Values.rabbitmq.erlangCookie | default "SWQOKODSQALRPCLNMEQG" | quote }}
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.auth.username | default "rabbitmq" | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "nomad-oasis.fullname" . }}-secret
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_DEFAULT_VHOST
              value: "/"
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - --silent
                - --quiet
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - --silent
                - --quiet
                - ping
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
      volumes:
        - name: data
          {{- if .Values.rabbitmq.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "nomad-oasis.fullname" . }}-rabbitmq
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
