apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nomad-oasis.fullname" . }}-secret
  labels:
    {{- include "nomad-oasis.labels" . | nindent 4 }}
type: Opaque
data:
  NOMAD_SERVICES_API_SECRET: {{ include "nomad-oasis.apiSecret" . | b64enc | quote }}
  {{- if .Values.north.enabled }}
  NOMAD_NORTH_JUPYTERHUB_CRYPT_KEY: {{ include "nomad-oasis.jupyterhubCryptKey" . | b64enc | quote }}
  {{- end }}
  {{- if .Values.rabbitmq.enabled }}
  RABBITMQ_PASSWORD: {{ include "nomad-oasis.rabbitmqPassword" . | b64enc | quote }}
  {{- end }}
